---
# tasks file for pycharm

- name: install tar on Fedora 24
  dnf:
    name: tar
    state: present
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == "24"

- name: Create directories for PyCharm
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ pycharm_download_directory }}"
  - "{{ pycharm_install_directory }}"
  - "{{ pycharm_desktop_file_location | dirname }}"


- name: Download PyCharm plugins
  get_url:
    url: "{{ pycharm_plugin_download_mirror }}{{ item }}"
    dest: "{{ pycharm_download_directory }}"
  register: pycharm_plugins
  with_items: "{{ pycharm_plugins }}"

- name: Install PyCharm
  unarchive:
    copy: no
    src: "{{ pycharm_download_url}}"
    dest: "{{ pycharm_install_directory }}"
    creates: "{{pycharm_location }}/bin/pycharm.sh"

- name: Install PyCharm Plugins
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ pycharm_location }}/plugins"
  with_items: "{{ pycharm_plugins.results }}"

- name: Create PyCharm Community Edition desktop entry
  template:
    src: pycharm.desktop.j2
    dest: "{{ pycharm_desktop_file_location }}"
